### ISSUE TITLE
add configurations to openhim in JetStream environment 

### ISSUE THREAD

**Issue by jennifershivers** [OpenConceptLab/ocl_datim#106]
get link to openHim installed in OpenMRS environment.  (Burke / Maurya) 
has cert been established etc?  (Maurya) 
Once system is running use admin account and add an account for self (Jen) 
add configurations from the digital Ocean version (Jen)

**Comment by paynejd** [comment]
Any update on this?

**Comment by maurya** [comment]
Update: To moving to Jetstream, we need a dockerized way for installing the mediators as well for them to be persistent. We have a docker-compose file for getting the core OpenHIM up and running. I have had a discussion with Burke to get some idea on how to do that and reached out to the OpenHIM interoperability layer community if they have any suggestions. But this will take a little more time on moving to jetstream.

**Comment by paynejd** [comment]
moving to new repo
