### ISSUE TITLE
DATIM testing and validation of OCL-linked landing page

### ISSUE THREAD

**Issue by jennifershivers** [OpenConceptLab/ocl_datim#107]

**Comment by paynejd** [comment]
I went ahead and started this on my flight over to Indi using the preliminary MER diff results with results tabulated here:
https://docs.google.com/spreadsheets/d/1B5AvGmIHRP-VkCnXBZIL0k-qJ0cGUliVyKvUUo1n1j0/edit#gid=0

There are 71 collections in OCL represented here, which were each requested through the OCL/Clearinghouse Mediator (i.e. OHIE landing page) and compared to the corresponding link in the DHIS2 landing page. 45 had no substantive difference and 26 had at least one diff. Note that a few were off by several hundred concepts.

Based on these preliminary results, some improvements are needed to make the E2E diff output easier to analyze and interpret.

**Comment by paynejd** [comment]
First analysis completed and available here -- we're reviewing this with PEPFAR on Nov 13:
https://docs.google.com/presentation/d/14WS5vKtee8_uyprEud4AckYOTVqsLsAAM2xBpvR9mnY/edit#slide=id.g29a9f22e61_0_135

**Comment by paynejd** [comment]
Moving to new PEPFAR DATIM-OCL repo
