### ISSUE TITLE
Internal (RI / Apelon) testing of metadata links

### ISSUE THREAD

**Issue by jennifershivers** [OpenConceptLab/ocl_datim#108]

**Comment by paynejd** [comment]
First round of E2E results for this are documented here and we are discussing with PEPFAR on Nov 13: https://docs.google.com/presentation/d/14WS5vKtee8_uyprEud4AckYOTVqsLsAAM2xBpvR9mnY/edit#slide=id.g29a9f22e61_0_135

Shifting this now to the next Sprint

**Comment by paynejd** [comment]
Moved to new PEPFAR DATIM-OCL repo
