### ISSUE TITLE
GET and POST of some repository exports returns 409 Conflict

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_datim#119]
There is one export (maybe 2...) that I was not able to create even after redeploying the staging server and after deleting and recreating the repository version (with the same and with different repo version IDs):

* https://api.staging.openconceptlab.org/orgs/PEPFAR/collections/MER-T-Community-FY16/v2017-10-02/export/

The export returns 409 Conflict when doing either a GET or a POST

I'm not sure where the error is on this one, if it's a server time out, or if it's in the export creation.

**Comment by davetrig** [comment]
@paynejd, can you look in the db and see if the MER-T-Community-FY16/v2017-10-02 collection version has _ocl_processing set to True?  That would return a 409 response.

You could also check the log -- if the 409 was returned because _ocl_processing=True, there would be lines in the log stating:
```
Collection Export requested for version v2017-10-02
    Collection Version is processing
```
If this is the case, then it's a question of the _ocl_processing flag being stuck.  Were there any collection exports that were successful? Wondering is this is a problem specific to collections.

**Comment by paynejd** [comment]
@davetrig It doesn't look like it. You can check through the web site
actually by using the debug flag, like this:

https://staging.openconceptlab.org/orgs/PEPFAR/collections/MER-T-Community-FY16/versions/?debug=1

**Comment by davetrig** [comment]
@paynejd The only other reason I can see that you'd get a 409 is if the export was already queued (see code below).  Any way to check that?

```
    def handle_export_collection_version(self):
        version = self.get_object()
        try:
            export_collection.delay(version.id)
            return 202
        except AlreadyQueued:
            return 409

```

**Comment by paynejd** [comment]
For that I would need access to the server -- Maybe Rafal can help us with
that tomorrow.

Is this method only called for POSTs though? I was receiving a 409 on both
POST and GET.

**Comment by davetrig** [comment]
Good point.  The only thing that would cause a 409 on both GET and POST is the _ocl_processing field.

The message in the log that I mentioned is a debug statement, so it might not be present in the log, depending on the logging level.  I think _ocl_processing is a hidden field.  I verified that is does not appear in the web site using the debug flag on in my OCL instance, even though I can see the field in the db.

I'm assuming that to look in the db, we'd need Rafal as well.

I don't know why that flag might get stuck.  In my local instance I can create a collection version, and the flag gets set to False at the end.  It's not at all possible that the version is actually still processing, is there?

**Comment by paynejd** [comment]
One export is still failing: /orgs/PEPFAR/collections/MER-T-Community-FY16/

But the other one is now working: /orgs/PEPFAR/collections/MER-T-Community-FY16/

@rkorytkowski I think we are going to need your help on this one to look in the database at the ocl_processing attribute. It's possible that it got stuck to true when celery failed last week, but we're not sure. This is a blocker to finalizing the MER content. Thanks!

**Comment by davetrig** [comment]
I added a view to sources and collections that will allow the user to query and clear the ocl_processing flag on source and collection versions.  The URL is the same as the export URL, with 'processing' replacing 'export'.
This view's GET will return the current value of the version's ocl_processing flag.  A POST will set the ocl_processing flag to False.
The commit also includes relevant integration tests.
I wanted to restrict the POST to 'staff' and 'super' users, but I could not get the user passed into the request.  Relevant code is commented out if you want to try it.

This commit got lumped in with my pull request for issue 115, because I forgot to create a new branch. Sorry.

**Comment by davetrig** [comment]
I closed the previous pull request, because I screwed up a merge from upstream.
I have created a new pull request for just this change.

**Comment by paynejd** [comment]
Cool! After this gets merged, please make sure to update the API docs to
reflect the new view (if you haven't already done so)

**Comment by rkorytkowski** [comment]
In fact _ocl_processing was set to true for the conflicting collection...

I'm testing your changes.

**Comment by rkorytkowski** [comment]
@davetrig, I'm thinking in addition to what you did, we should also set _ocl_processing to false for all collections and sources when starting up the server.

**Comment by paynejd** [comment]
There is now another export (for a new repo version) that is failing with 409 conflict:

https://staging.openconceptlab.org/orgs/PEPFAR/collections/MER-R-Facility-FY16Q1Q2Q3/v2017-10-13T100044.037131/concepts/

I think this is an area that we're going to have to do some more investigation.

**Comment by davetrig** [comment]
@rkorytkowski I added the automatic clearing of the _ocl_processing flags to system startup, as you suggested.  That was a very good idea.  The pull request for this branch should now include this commit.

I did not rename import_lookup_values, as I wanted to keep the impact to existing code to a minimum.

**Comment by rkorytkowski** [comment]
Merged and fixed authentication in https://github.com/OpenConceptLab/oclapi/commit/d96062d8ba25b607c8d990226e2995b91dd4a3f7

Dave, please always include issue id e.g. DATIM-Metadata-Project#119 at the beginning of each commit message.

**Comment by rkorytkowski** [comment]
Deploying to staging...

**Comment by rkorytkowski** [comment]
https://api.staging.openconceptlab.org/orgs/PEPFAR/collections/MER-R-Facility-FY16Q1Q2Q3/v2017-10-02/processing/ fails with:

api_1     | ERROR 2017/10/16 09:42:52 [base.py:210 handle_uncaught_exception()] Internal Server Error: /orgs/PEPFAR/collections/MER-R-Facility-FY16Q1Q2Q3/v2017-10-02/processing/
api_1     | Traceback (most recent call last):
api_1     |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
api_1     |     response = callback(request, *callback_args, **callback_kwargs)
api_1     |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
api_1     |     return self.dispatch(request, *args, **kwargs)
api_1     |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
api_1     |     return view_func(*args, **kwargs)
api_1     |   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 327, in dispatch
api_1     |     response = self.handle_exception(exc)
api_1     |   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 324, in dispatch
api_1     |     response = handler(request, *args, **kwargs)
api_1     |   File "/code/collection/views.py", line 463, in get
api_1     |     version = self.get_object()
api_1     |   File "/code/oclapi/views.py", line 74, in get_object
api_1     |     obj = get_object_or_404(queryset, **filter_kwargs)
api_1     |   File "/code/oclapi/views.py", line 23, in get_object_or_404
api_1     |     return generics_get_object_or_404(queryset, **filter_kwargs)
api_1     |   File "/usr/local/lib/python2.7/site-packages/rest_framework/generics.py", line 23, in get_object_or_404
api_1     |     return _get_object_or_404(queryset, **filter_kwargs)
api_1     |   File "/usr/local/lib/python2.7/site-packages/django/shortcuts/__init__.py", line 113, in get_object_or_404
api_1     |     return queryset.get(*args, **kwargs)
api_1     |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 407, in get
api_1     |     (self.model._meta.object_name, num))
api_1     | MultipleObjectsReturned: get() returned more than one CollectionVersion -- it returned 53!

@davetrig , could you please try to reproduce it locally? Maybe collection name or version from url is not parsed correctly and the query is not limiting the results correctly... Not sure what else it can be.

**Comment by rkorytkowski** [comment]
Note that other URLs like https://api.staging.openconceptlab.org/orgs/PEPFAR/collections/MER-R-Facility-FY16Q1Q2Q3/v2017-10-02/references/ or https://api.staging.openconceptlab.org/orgs/PEPFAR/collections/MER-R-Facility-FY16Q1Q2Q3/v2017-10-02/ work as expected...

**Comment by davetrig** [comment]
@rkorytkowski & @paynejd 
I managed to replicate the problem. It looks like it's searching for version id without organization or collection -- which makes no sense, as I copied the code from the "export" view, which works as expected.  I'll update as soon as I have a solution.

**Comment by davetrig** [comment]
I found the problem.  I didn't copy everything properly from "export" when I made "processing".  I'll have a pull request ready soon.

**Comment by davetrig** [comment]
Pull request submitted

**Comment by rkorytkowski** [comment]
Thanks @davetrig! Merged in https://github.com/OpenConceptLab/oclapi/commit/f4099b85ef97df381da60c84b61d24ac3373761e

**Comment by paynejd** [comment]
@rkorytkowski Is this code deployed?

@davetrig Were the new API requests added to the API documentation?

**Comment by rkorytkowski** [comment]
Yes, it's been deployed to all envs... 

One more thing I noticed is that the export endpoint returns 409 also when the index is being built, but the export is actually ready. I think the issue with the flag may be that there are 2 tasks, which concurrently update the flag: building index and creating export. If they happen to run in a bad sequence then we may end up with the flag not being cleared. I will investigate further how to eliminate that risk.

**Comment by davetrig** [comment]
Changes added to API documentation

**Comment by paynejd** [comment]
Rafal, does export creation rely on the index or does it only use Mongo? If
it relies on the index and building the index sometimes takes longer than
creating the export, then wouldn't that result in exports missing some
resources?

**Comment by rkorytkowski** [comment]
It uses only Mongo.

**Comment by rkorytkowski** [comment]
Committed fixes in https://github.com/OpenConceptLab/oclapi/commit/4b3970431559cd4244bd74fa5639e11448b31243 and https://github.com/OpenConceptLab/ocl_web/commit/bc20eb798a4cfa286031cfdd917ad352b566a828

Basically we are now storing celery process ids in db (pushed and pulled atomically to avoid overwriting) and asking celery if process is terminated to discover cases when it failed to unset the processing flag. I also added try/finally blocks on all celery tasks to clear processing flag on any exception.

**Comment by rkorytkowski** [comment]
It's been deployed to staging.
