### ISSUE TITLE
Sustainable fix for long-running processes

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_datim#125]
We increased API request timeout to 10min as a temporary fix for completing long-running import processes. Specifically, this is when bulk POSTing references to a collection. Repository version POSTs are also sometimes long-running and timeout at 60sec.

10min timeout may be long enough that we run into some server instability issues again, so we may need to find a better long-term solution.

This will stay in the back log until after we have tested the new repository version models for linking to concepts and mappings, as that may provide enough performance improvement to resolve this issue entirely and then we can switch back to a shorter timeout.

**Comment by rkorytkowski** [comment]
Changes introduced in #102 do not improve handling collections. They are only for sources. Collections have not been optimized in any way, but definitely a similar approach could be taken.

**Comment by rkorytkowski** [comment]
Created #137 to address fixing performance for collections.

**Comment by paynejd** [comment]
This ticket will be closed in favor of more specific tickets as needed
