### ISSUE TITLE
Address performance issues with collections

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_datim#137]
Collections are performing badly when it comes to both reads and writes. It's unacceptable for the fetch of 25 items on a collection of 2000 items to take ~10 seconds. Imports are similarly slow. The issue also impacts solr indexing. Things get worse when the number of items grows.

Collections need to be remodeled similar as in #102. It's a bit more complex as we need to account for dynamic reference resolution of concepts and mappings belonging to a collection.

@paynejd, please confirm that I understand the logic correctly. When you create a new version of a collection and have references to concepts and not specific concept versions, then that collection version will be created using a specific concept version (latest at the time of version creation). In other words references will never be evaluated again for a collection version other than HEAD.

**Comment by paynejd** [comment]
@rkorytkowski Sorry that I missed your question here! You are correct in your analysis -- references to HEAD are resolved to a specific concept/mapping version at the time of repo version creation.

**Comment by paynejd** [comment]
moved to new ocl_issues repo -- closing out
