### ISSUE TITLE
Refresh active counts of concepts and mappings within repos and repo versions

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_datim#156]
Some of these counts are incorrect, probably due to historical errors that do not seem to be happening now, so this is may be a one-time thing, but we could keep the "fix-it" script around in case it does happen again -- Also note that this will only have noticeable impact on PEPFAR if they are directed to the actual OCL interface or if they begin to use the API directly

**Comment by rkorytkowski** [comment]
The count of active concepts and mappings should not be stored in db. It's a very simple and performant query to calculate the value whenever it is needed. It will not be prone to out-of-sync errors.

**Comment by paynejd** [comment]
Good that makes more sense to me -- I was never sure why it was stored in
the version object. Is that a big task to switch?

**Comment by rkorytkowski** [comment]
I think 3 is a fair estimate.

**Comment by rkorytkowski** [comment]
Could you please clarify what is an active concept?

**Comment by paynejd** [comment]
Active resource counts apply to repository versions for both sources and
collections. For a the parent repository object (if relevant), active
resource counts should return the active resource counts for the HEAD
repository version.

For source versions:
* Active concept = the number of non-retired concept versions in the repo
version
* Active mapping = the number of non-retired mapping versions in the repo
version

For collection versions:
* Active concept = the number of non-retired concept versions referenced in
the repo version
* Active mapping = the number of non-retired mapping versions referenced in
the repo version
* References = the number of references in the repo version (note that
there are no "retired" references)

**Comment by rkorytkowski** [comment]
Fixed in https://github.com/OpenConceptLab/oclapi/commit/a710cbba60cbb469b62eb8a877e49f40757b9951

**Comment by paynejd** [comment]
Before we close this out -- did you change all of the count attributes to
be dynamic? Or just concepts and mappings? I know the ticket was focused on
concepts/mappings, and I'm wondering if we should create a separate ticket
for all of the other counts in the system.

**Comment by rkorytkowski** [comment]
It appears that count() is not performing as fast as I thought on MongoDB. I need to revert it.

**Comment by rkorytkowski** [comment]
@paynejd, what are other count attributes?

**Comment by paynejd** [comment]
Here are the counts currently, but before diving into this, we should
decide what the counts *should* be.

*Orgs:*

 "members": 2,
    "public_collections": 1,
    "public_sources": 1,


*Users:*

 "orgs": 3,
    "public_collections": 3,
    "public_sources": 1,


*Source and Collection (and I think repo versions too)*

"versions": 3,
    "active_concepts": 15000,
    "active_mappings": 3243,


*Collections may also have a count of: *"references"

**Comment by rkorytkowski** [comment]
Fixed in https://github.com/OpenConceptLab/oclapi/commit/a320c5a55d578a6505a5d15400c41801ab5f97a1
I made it to be synced on every restart, but also whenever a source/collection is saved.

**Comment by rkorytkowski** [comment]
Okay, let's address other counters as well. I'll try to look up in code what they are right now.

**Comment by rkorytkowski** [comment]
All the counters you mentioned are dynamically calculated using .count() except for active_concept and active_mappings, which are calculated on each save. I haven't found count of references on collections.

I don't think we need to cache the other counters at this point. We may want to do that once we hit performance limits, but up till now number of collections, sources and users is not that big to make a difference.
