### ISSUE TITLE
Switch from dev-de to dhis2 triage server that is updated nightly

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_datim#160]

**Comment by paynejd** [comment]
@jennifershivers to get user account to triage server

@maurya to update sync scripts with new user account

**Comment by maurya** [comment]
@jennifershivers , is the triage server -  triage.ug.datim4u.org?

**Comment by jennifershivers** [comment]
no.  we want to use the triage server for global datim.  I need to look up the server and then find out which github to post this in.

**Comment by jennifershivers** [comment]
https://triage.datim.org/dhis-web-commons/security/login.action

**Comment by jennifershivers** [comment]
requested - Need a whitelisted account for the DATIM metadata project on https://triage.datim.org #2833

**Comment by paynejd** [comment]
Any update on this?

**Comment by jennifershivers** [comment]
Need a whitelisted account for the DATIM metadata project on https://triage.datim.org #2833 - has not been updated.

**Comment by paynejd** [comment]
Any progress here?

**Comment by paynejd** [comment]
Moved to new phase 3 repo - closing
