### ISSUE TITLE
Business and Functional Gap Analysis of FHIR

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_datim#173]
(Continuation of #170)

Suggest that @cmac35 and @davetrig lead this effort -- please pull in @jennifershivers and as much as is helpful!

Business and Functional Gap Analysis - Estimated Four (4) Business Days
* Document and validate PEPFAR DATIM requirements
* Review the FHIR CodeSystem, ValueSet and ConceptMap resources and the applicable operations.
* Compare the existing OCL API and REST services to identify gaps in OCL
* Confer with OpenHIE Terminology Services and/or FHIR Terminology Services communities

Additional documentation available here: https://docs.google.com/presentation/d/14WS5vKtee8_uyprEud4AckYOTVqsLsAAM2xBpvR9mnY/edit#slide=id.p

**Comment by jennifershivers** [comment]
I am wondering if one requirement is to be able to export the indicator mapping for a specific country.

**Comment by cmac35** [comment]
@jennifershivers  I think exporting an indicator mapping for a specific country could be one of our critical path test cases. Dependency on the ticket for loading of the indicator mappings in the pre-coordinated fashion we showed Mike.

**Comment by paynejd** [comment]
*1. Indicator Transform Requests*
1.a. Given a MOH indicator, give me the "equivalent" PEPFAR indicator
1.b. Given a PEPFAR indicator, give me the "equivalent" indicator for a
specified country
1.c. *(Optional)* Given a PEPFAR indicator, give me "equivalent" indicators
for all PEPFAR countries

*2. Indicator-Disaggregate Pair Transform Requests*
2.a. Given MOH indicator-disaggregate pair, give me the "related" PEPFAR
indicator-disaggregate pair
2.b. Given PEPFAR pair, give me the list of one or more "related" pairs for
a specified country
2.c. *(Optional)* Given PEPFAR pair, give me the list of one or more
"related" pairs for each PEPFAR country

However, I think that the main question that PEPFAR wants to answer with
the API is slightly different:
"Given a particular PEPFAR indicator-disaggregate pair, give me all of the
country-level mappings and indicator-disaggregate pairs that I need in
order to calculate it"

I believe that we can answer this question using 2.b. above.

Are there other transactions?

Carol, could you help us map out how each of the above would be
accomplished using FHIR?

**Comment by cmac35** [comment]
I met with Dave today and this work is underway. I'll touch base with you on Friday @paynejd to discuss where we are. @davetrig may reach out for validation on sample content. Otherwise, still looks good to have this complete for our conversation with Mike on Monday
