### ISSUE TITLE
2 types of "CSV Download" errors

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_datim#185]
OCL has CSV download links for most search results and lists that are returned. For example, see the URL and screenshot below. Usually, clicking the "Formatted CSV" link returns the expected CSV file. Occasionally, it instead returns a compressed `gz` of the CSV file. And every so often, it shows an error message of "Something unexpected happened" with a "Server 500" error shown in the Javascript console.

Here are two of the links that resulted in Server 500 errors:
* https://api.qa.openconceptlab.org/orgs/CSA/sources/HMISindicators/V1.0/concepts/?csv=true&user=zelalem
* https://api.qa.openconceptlab.org/orgs/FMoH/sources/HMIS/v1.1/concepts/?csv=true&user=olik&type=repoSearch

Here's an example of the CSV download feature:
https://staging.openconceptlab.org/orgs/EthiopiaNHDD/sources/HMIS-Indicators-2017/concepts/
![image](https://user-images.githubusercontent.com/1189689/33832054-8a5c14ac-de8b-11e7-8c8c-6035a71f537e.png)

**Comment by rkorytkowski** [comment]
The 505 server error is:
`api_1     | [u"TypeError: 'NoneType' object is not iterable", u'  File "django/core/handlers/base.py", line 113, in get_response', u'  File "django/views/generic/base.py", line 68, in view', u'  File "django/views/decorators/csrf.py", line 77, in wrapped_view', u'  File "concepts/views.py", line 167, in dispatch', u'  File "django/views/generic/base.py", line 68, in view', u'  File "django/views/decorators/csrf.py", line 77, in wrapped_view', u'  File "rest_framework/views.py", line 327, in dispatch', u'  File "rest_framework/views.py", line 324, in dispatch', u'  File "concepts/views.py", line 254, in get', u'  File "oclapi/mixins.py", line 61, in list', u'  File "oclapi/mixins.py", line 138, in get_csv', u'  File "oclapi/mixins.py", line 204, in get_csv_rows', u'  File "oclapi/mixins.py", line 226, in get_formatted_values']`

**Comment by rkorytkowski** [comment]
Fixed in the 500 issue in https://github.com/OpenConceptLab/oclapi/commit/eeb23209907f900d145a55167615e78e62ac9c52

**Comment by rkorytkowski** [comment]
The problem with gzip content is that currently browsers by default ungzip the file when downloading. You can simply rename .csv.gz to .csv after downloading. Of course we don't want users to have to do that. The issue is if we put the .gz file on S3 then the .gz extension will always be in the url. If we skip the .gz extension then we will assume all clients will handle gzip compression on the fly, which is not the case.

One solution is to put ungzipped csv's on S3. They can be gizipped and cached by S3 on the fly when a client adds "Content-Encoding: gzip" to a request header (all browser do that). The issue is we will use up more space on S3 for storing ungzipped csv's.

The other solution is to store files compressed with zip or tgz, which are not decoded on the fly by browsers. I'm in favor of this solution. It would be good to unify the compression method for export endpoints as well, which currently returns .tar.gz. Zip is more friendly for Windows users.

**Comment by rkorytkowski** [comment]
@paynejd let me know what you think.

**Comment by rkorytkowski** [comment]
@paynejd ping

**Comment by paynejd** [comment]
There are a few different types of downloads:

   - Exports -- these should always be compressed
   - CSVs --
   - Limited CSV results -- these are automatically limited to 100 results
      (although we may want to remove or increase this limit in the future)
      - Full CSV results -- when a dictionary owner downloads all concepts
      or mappings in a dictionary

It would be ideal to use a common format across all of them. If possible,
we would want to avoid requiring users to take an extra step to decompress
the "limited CSV results" before opening them, but that may not be a big
issue. I'm okay to go with a single compression method of Zip.

**Comment by rkorytkowski** [comment]
Are limited csv results currently returned without compression anywhere in the application? I couldn't find any evidence in code...

**Comment by rkorytkowski** [comment]
Changed to using zip as a compression method for downloads in  https://github.com/OpenConceptLab/oclapi/commit/63c238a898cd64172c16360e43364c22ea81dbfe

**Comment by paynejd** [comment]
I do not think there are any instances of results returned without
compression currently.

**Comment by rkorytkowski** [comment]
Okay! I think it needs a separate issue then as it is a new feature. We need to consider how to implement it on the API level e.g. require zip=false header to return unzipped content. Do we return an error if the limit is set over 100 and require zip=false?

**Comment by paynejd** [comment]
I like the approach of creating a new ticket for a zip=false attribute.
However, I'm not confident that the 100 record limit was implemented
correctly, or at minimum, it is not well documented so it is confusing to
users when they only receive 100 records for a larger dictionary. we can
put this into the back log for now, but will need to deal with it before
long.
