### ISSUE TITLE
Add mappings and custom attributes to Concept CSV downloads

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_datim#190]
The lack of mappings and custom attributes in the Concept CSV downloads makes them unusable for most stakeholders. Short-term approach could be to just add 2 columns:

* Mappings -- for a source, this is a list of mappings stored in the same source as the concept for which the concept is the "from concept"; for a collection, this is a list of mappings stored in the same collection for which the concept is the from concept; e.g.:
```
CIEL / CIEL / 1049 : Malaria <SAME-AS> WHO / ICD-10-WHO / G09.8 : Malaria, Unspecified [External]
```
Or generically:
```
[from-owner] / [from-source] / [from-concept-code] : [from-concept-name] <map-type> [to-owner] / [to-source] / [to-concept-code] (: [to-concept-name]) [Internal/External]
```
Where [to-concept-name] is optional for external mappings, and [Internal/External] is evaluated on the fly.

* Attributes -- semicolon separated list of name-value pairs, e.g.:
```
attr1: value of attribute 1; attr2: value of attribute 2
```

**Comment by rkorytkowski** [comment]
Done in https://github.com/OpenConceptLab/oclapi/commit/7e4a32ff276b3b1dfc39c69b13b13e62c59c446f
