### ISSUE TITLE
Export of sources/collections are not returning zip results

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_datim#199]
Broken endpoints:
https://api.staging.openconceptlab.org/orgs/PEPFAR/collections/MER-T-Operating-Unit-Level-IM-FY17/v2017-10-02T101905.267394/export/

https://api.staging.openconceptlab.org/orgs/PEPFAR/sources/Mechanisms/v2018-01-13T004813.005885/export/

https://api.staging.openconceptlab.org/orgs/PEPFAR/collections/SIMS3-Facility/v2017-10-11T175154.910319/export/

**Comment by paynejd** [comment]
moved to new ocl_issues repo - closing out
