### ISSUE TITLE
Plan for importing MER indicator descriptive text

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_datim#63]
See here:
https://www.pepfar.gov/documents/organization/263233.pdf

Hopefully all of this descriptive text is available in DHIS2, but we need to confirm this. Here's the template for the MR indicator definitions:

![image](https://user-images.githubusercontent.com/1189689/29292180-2827b2f2-8114-11e7-8190-454e6c870b0a.png)

**Comment by maurya** [comment]
Hi John,

I couldn't  find the exact indicators in that document in Dev-de system. 
I tried looking through normal indicators - and I don't think they are storing all this data in DHIS2 or it is not very apparent. The attributes being saved from the above table are - 

- Name
- Numerator
- Denominator
- Description

<img width="1624" alt="screen shot 2017-08-18 at 9 16 50 am" src="https://user-images.githubusercontent.com/1560244/29460683-d6e30d84-83f6-11e7-934a-b61febf252a1.png">
<img width="1652" alt="screen shot 2017-08-18 at 9 18 16 am" src="https://user-images.githubusercontent.com/1560244/29460684-d6e33548-83f6-11e7-9c65-85ae1d70d19c.png">

**Comment by paynejd** [comment]
Not required to meet clearinghouse requirements, but will demonstrate for testing purposes

**Comment by paynejd** [comment]
out of scope -- closing
