### ISSUE TITLE
Find a way to use PyCharm debugger with Docker for ocl_web

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/ocl_datim#64]
#15 added docker config, but I could not make it work with the PyCharm debugger, which needs to be investigated further....

**Comment by rkorytkowski** [comment]
Documented at https://github.com/OpenConceptLab/ocl_web/blob/master/README.md#debugging

**Comment by paynejd** [comment]
Switching to milestone 5

**Comment by rkorytkowski** [comment]
@paynejd, did you have a chance to test it?

**Comment by paynejd** [comment]
Hi all, I'm happy to test this, but will need help!
