### ISSUE TITLE
Document server admin and maintenance plan

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_datim#79]

**Comment by bmamlin** [comment]
@paynejd, I'm happy to help draft something up. I don't think we have anything formal within the OpenMRS Infrastructure team. We basically share a private wiki within the ITSM group with instructions on how to manage assets.

If we need a formal plan with some hard guarantees/expectations, then it may require investment into infrastructure support beyond volunteerism.

**Comment by paynejd** [comment]
closing - replaced by phase 3 tasks
